// v1.0.1 - Force refresh for new VAPID keys
import { precacheAndRoute } from 'workbox-precaching';

// Precache assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Handle push events - this is where we show the notification
self.addEventListener('push', function (event) {
    if (!(self.Notification && self.Notification.permission === 'granted')) {
        return;
    }

    if (event.data) {
        try {
            const data = event.data.json();
            const { title, body, icon, url, data: customData } = data;

            event.waitUntil(
                self.registration.showNotification(title || 'New Notification', {
                    body: body || '',
                    icon: icon || '/icon-192.png',
                    badge: '/icon-192.png',
                    data: {
                        url: url || '/',
                        ...customData
                    }
                })
            );
        } catch (e) {
            console.error('Error parsing push data:', e);
            // Fallback notification if parsing fails
            event.waitUntil(
                self.registration.showNotification('HRIS Notification', {
                    body: 'You have a new update.',
                })
            );
        }
    }
});

// Handle notification clicks
self.addEventListener('notificationclick', function (event) {
    event.notification.close();

    const urlToOpen = event.notification.data.url;

    event.waitUntil(
        self.clients.matchAll({
            type: 'window',
            includeUncontrolled: true
        }).then(function (clientList) {
            for (let i = 0; i < clientList.length; i++) {
                const client = clientList[i];
                if (client.url === urlToOpen && 'focus' in client) {
                    return client.focus();
                }
            }
            if (self.clients.openWindow) {
                return self.clients.openWindow(urlToOpen);
            }
        })
    );
});

// Handle periodic background sync - hourly check for new notifications
self.addEventListener('periodicsync', (event) => {
    if (event.tag === 'check-notifications') {
        event.waitUntil(checkNewNotifications());
    }
});

async function checkNewNotifications() {
    try {
        const response = await fetch('/notifications/unread');
        if (!response.ok) return;

        const notifications = await response.json();
        
        for (const notification of notifications) {
            // Show notification
            await self.registration.showNotification(notification.title, {
                body: notification.body,
                icon: '/icon-192.png',
                badge: '/icon-192.png',
                data: {
                    url: notification.url
                },
                tag: `unread-${notification.id}` // Use unique tag to prevent duplicates
            });
        }
    } catch (error) {
        console.error('Periodic sync fetch failed:', error);
    }
}
